### ISSUE TITLE
vite-plugin-inspect causes the local vite service to fail to start

### ISSUE THREAD

**Issue by yiyi-an** [antfu/vite-plugin-inspect#107] opened 2024-01-25 02:49 UTC
### Describe the bug

vite.config.js has a configuration similar to the following,

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, './env', '')
  return {
    plugins: [
      vue(),
      vueJsx(),
      InspectPlugin()
    ],
  }
})

After building with vitejs,The console outputs the following error to me

[vite] require() of ES Module /Users/fifa/Desktop/isj-work/aippt-web/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/lodash.js from /Users/fifa/Desktop/isj-work/aippt-web/node_modules/.pnpm/vite-plugin-inspect@0.8.2_vite@4.5.2/node_modules/vite-plugin-inspect/dist/index.cjs not supported.
Instead change the require of lodash.js in /Users/fifa/Desktop/isj-work/aippt-web/node_modules/.pnpm/vite-plugin-inspect@0.8.2_vite@4.5.2/node_modules/vite-plugin-inspect/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.

When I comment out the line "InspectPlugin() ". The project is running properly

Project devDependencies package version：
├── vue@3.4.15 
├── vite-plugin-inspect@0.8.2 
├── vite@4.5.2 

### Reproduction

sorry

### System Info

```Shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 72.39 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
    pnpm: 8.12.1 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.234
    Edge: 120.0.2210.144
    Safari: 17.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by LoTwT** [comment] 2024-01-25 07:49
Hi, please try `v0.8.3`.

**Comment by sxzz** [comment] 2024-01-25 08:58
Seems like duplicate of #105

**Closed by sxzz** 2024-01-25 08:58 UTC
